### ISSUE TITLE
Can not instantiate GuzzleHttp\ClientInterface.

### ISSUE THREAD

**Issue by vggalkin** [gietos/yii2-dadata#1]
Not instantiable – yii\di\NotInstantiableException
Can not instantiate GuzzleHttp\ClientInterface.
1. in ..../vendor/yiisoft/yii2/di/Container.php at line 373

**Comment by kstkn** [comment]
You probably miss dependency registration for `GuzzleHttp\ClientInterface`. See https://www.yiiframework.com/doc/guide/2.0/en/concept-di-container#registering-dependencies
